apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crud-api
  name: crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-api
  strategy: {}
  template:
    metadata:
      labels:
        app: crud-api
    spec:
      containers:
      - args:
        - mvn
        - clean
        - spring-boot:run
        image: {{ .Values.crudAPI.image.repository }}:{{.Values.crudAPI.image.tag}}
        name: crud-api-k8
        resources: {}