apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui-vuejs
  name: ui-vuejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-vuejs
  strategy: {}
  template:
    metadata:
      labels:
        app: ui-vuejs
    spec:
      containers:
      - args:
        - mvn
        - clean
        - spring-boot:run
        image: {{ .Values.uiVuejs.image.repository }}:{{.Values.uiVuejs.image.tag}}
        name: ui-vuejs-k8
        resources: {}
